rvm:
  - 2.1.2
  - ruby-head
  - jruby
  - jruby-head
  - rbx

matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS='--2.0'
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true

script: bundle exec rspec spec && bundle exec cucumber
